/* ============================================================
   WORLD CUP '26 — RETRO FAN ZONE
   data.js — all 48 qualified nations
   kit.pattern: solid | stripes | hoops | checks | sash
   ============================================================ */

const TEAMS = {

  /* ---------------- GROUP A ---------------- */
  mex: {
    name: "MEXICO", flag: "🇲🇽", group: "A", lat: 23.6, lon: -102.5,
    tagline: "EL TRI — HOST NATION",
    kit: { p: "#046A38", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#C8102E" },
    bg: { g1: "#0b3d1e", g2: "#2e8b57", motifs: ["🌮", "🌵", "💀", "🎺"] },
    knownFor: "Aztec pyramids, mariachi, lucha libre and the loudest home crowd in the tournament — the Estadio Azteca has hosted two World Cup finals and opened this one.",
    sights: ["Teotihuacán pyramids", "Chichén Itzá (Yucatán)", "Mexico City's Zócalo & Frida Kahlo Museum"],
    foods: ["Tacos al pastor", "Mole poblano", "Tamales & churros"],
    culture: "A fusion of Aztec, Maya and Spanish colonial heritage: Día de los Muertos parades, mariachi serenades, lucha libre masks and murals by Diego Rivera.",
    legends: ["Hugo Sánchez", "Rafael Márquez", "Guillermo Ochoa", "Santiago Giménez"],
    wc: "18th appearance. Quarterfinalists in 1970 & 1986 — both at home. First nation to host three World Cups.",
    fact: "The 'Mexican Wave' went global at the 1986 World Cup in Mexico.",
    status: "🟨 WON GROUP A (9 PTS) → BEAT ECUADOR IN R32 → FELL 3-2 TO ENGLAND IN A ROUND-OF-16 THRILLER."
  },
  rsa: {
    name: "SOUTH AFRICA", flag: "🇿🇦", group: "A", lat: -28.8, lon: 24.5,
    tagline: "BAFANA BAFANA",
    kit: { p: "#FFB612", s: "#007749", pattern: "solid", shorts: "#007749", socks: "#FFB612" },
    bg: { g1: "#2b1a0a", g2: "#c96f1e", motifs: ["🦁", "🌍", "🥁", "☀️"] },
    knownFor: "Safari country — the Big Five, Table Mountain, vuvuzelas, and the rainbow nation spirit of Mandela. Hosted Africa's first World Cup in 2010.",
    sights: ["Table Mountain, Cape Town", "Kruger National Park", "Robben Island"],
    foods: ["Braai (barbecue)", "Bunny chow", "Biltong"],
    culture: "Eleven official languages, township jazz, gumboot dancing and a sporting culture that unites rugby, cricket and football under one flag.",
    legends: ["Lucas Radebe", "Benni McCarthy", "Percy Tau"],
    wc: "5th appearance. Hosted in 2010 — Siphiwe Tshabalala's opener is an all-time World Cup goal.",
    fact: "The vuvuzela's drone at the 2010 World Cup measured up to 120 decibels.",
    status: "🟩 RUNNER-UP GROUP A (4 PTS) → ELIMINATED 1-0 BY CANADA IN THE ROUND OF 32."
  },
  kor: {
    name: "SOUTH KOREA", flag: "🇰🇷", group: "A", lat: 36.3, lon: 127.9,
    tagline: "TAEGEUK WARRIORS",
    kit: { p: "#CD2E3A", s: "#0047A0", pattern: "solid", shorts: "#000000", socks: "#CD2E3A" },
    bg: { g1: "#1a0a14", g2: "#7a1f3d", motifs: ["🏯", "🎮", "🎤", "🌸"] },
    knownFor: "K-pop, kimchi, esports arenas and blazing-fast internet — plus the reddest, best-choreographed fan army in football.",
    sights: ["Gyeongbokgung Palace, Seoul", "Busan's Haeundae Beach", "Jeju Island volcanic coast"],
    foods: ["Kimchi & bibimbap", "Korean BBQ (samgyeopsal)", "Tteokbokki street food"],
    culture: "Ancient Confucian tradition meets hyper-modern pop culture: hanbok robes, temple stays, PC bangs and K-drama fandom.",
    legends: ["Cha Bum-kun", "Park Ji-sung", "Son Heung-min"],
    wc: "12th appearance — Asia's record. Semifinalists as co-hosts in 2002, the best Asian run ever.",
    fact: "The 2002 'Red Devils' street crowds in Seoul topped 7 million people on semifinal night.",
    status: "🟥 ELIMINATED IN GROUP A — SON'S FAREWELL CUP ENDED AT THE GROUP STAGE."
  },
  cze: {
    name: "CZECHIA", flag: "🇨🇿", group: "A", lat: 49.8, lon: 15.5,
    tagline: "THE NÁRODNÍ TÝM",
    kit: { p: "#D7141A", s: "#FFFFFF", pattern: "solid", shorts: "#11457E", socks: "#D7141A" },
    bg: { g1: "#0d1526", g2: "#31456e", motifs: ["🏰", "🍺", "🎻", "⏰"] },
    knownFor: "Fairy-tale Prague, castles on every hill, the world's best beer per capita and a golden footballing lineage from Masopust to Nedvěd.",
    sights: ["Charles Bridge & Prague Castle", "Old Town Astronomical Clock", "Český Krumlov"],
    foods: ["Svíčková (creamy beef)", "Trdelník chimney cake", "Pilsner Urquell"],
    culture: "Bohemian heartland of composers (Dvořák, Smetana), marionette theatre, beer halls and gothic spires.",
    wc: "First appearance as independent Czechia; Czechoslovakia reached two World Cup finals (1934, 1962).",
    legends: ["Josef Masopust", "Pavel Nedvěd", "Petr Čech", "Patrik Schick"],
    fact: "Czechs drink ~140 litres of beer per person per year — a world record.",
    status: "🟥 ELIMINATED IN GROUP A — THE COMEBACK CUP ENDED EARLY."
  },

  /* ---------------- GROUP B ---------------- */
  can: {
    name: "CANADA", flag: "🇨🇦", group: "B", lat: 56.1, lon: -106.3,
    tagline: "LES ROUGES — HOST NATION",
    kit: { p: "#D80621", s: "#FFFFFF", pattern: "solid", shorts: "#D80621", socks: "#D80621" },
    bg: { g1: "#1a0505", g2: "#7d1f28", motifs: ["🍁", "🏒", "🏔", "🦫"] },
    knownFor: "Maple syrup, the Rocky Mountains, politeness memes and a golden generation led by Alphonso Davies — co-hosting its first men's World Cup.",
    sights: ["Niagara Falls", "Banff & the Rockies", "CN Tower, Toronto"],
    foods: ["Poutine", "Maple syrup on everything", "Butter tarts"],
    culture: "A bilingual mosaic of First Nations heritage, French-Canadian joie de vivre and hockey-mad winters.",
    legends: ["Alphonso Davies", "Jonathan David", "Dwayne De Rosario"],
    wc: "3rd appearance. First World Cup goals ever scored in Qatar 2022; first knockout wins in 2026.",
    fact: "BMO Field in Toronto hosted Canada's first-ever home World Cup match in 2026.",
    status: "🟩 RUNNER-UP GROUP B (4 PTS) → BEAT SOUTH AFRICA 1-0 → FELL 3-0 TO MOROCCO IN THE ROUND OF 16."
  },
  bih: {
    name: "BOSNIA & HERZEGOVINA", flag: "🇧🇦", group: "B", lat: 43.9, lon: 17.7,
    tagline: "THE DRAGONS",
    kit: { p: "#002F6C", s: "#FECB00", pattern: "solid", shorts: "#002F6C", socks: "#FECB00" },
    bg: { g1: "#0a1226", g2: "#274b8f", motifs: ["🌉", "☕", "⛰", "🐉"] },
    knownFor: "The rebuilt Stari Most bridge of Mostar, Sarajevo's east-meets-west bazaars and a diaspora that fills stadiums anywhere in the world.",
    sights: ["Stari Most, Mostar", "Sarajevo's Baščaršija old bazaar", "Kravice Waterfalls"],
    foods: ["Ćevapi with somun bread", "Burek", "Bosnian coffee"],
    culture: "Ottoman minarets beside Austro-Hungarian facades; coffee served slow, football argued loudly.",
    legends: ["Edin Džeko", "Miralem Pjanić", "Asmir Begović"],
    wc: "2nd appearance after 2014 — and a first-ever trip to the knockout rounds in 2026.",
    fact: "Sarajevo hosted the 1984 Winter Olympics; its bobsled track is now a graffiti-art hike.",
    status: "🟩 ADVANCED FROM GROUP B AS A BEST 3RD → ELIMINATED 2-0 BY THE USA IN THE ROUND OF 32."
  },
  qat: {
    name: "QATAR", flag: "🇶🇦", group: "B", lat: 25.3, lon: 51.2,
    tagline: "THE MAROONS",
    kit: { p: "#8A1538", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#8A1538" },
    bg: { g1: "#1d0812", g2: "#6e1e3c", motifs: ["🏜", "🐪", "🏙", "⛵"] },
    knownFor: "Futuristic Doha skyline, desert dunes, pearl-diving heritage — and hosting the unforgettable 2022 World Cup final.",
    sights: ["Museum of Islamic Art, Doha", "Souq Waqif", "Khor Al Adaid 'Inland Sea' dunes"],
    foods: ["Machboos (spiced rice)", "Karak chai", "Luqaimat dumplings"],
    culture: "Bedouin hospitality, falconry, dhow boats and a skyline that grew from sand in a generation.",
    legends: ["Akram Afif", "Almoez Ali", "Hassan Al-Haydos"],
    wc: "2nd appearance. Hosts in 2022, Asian champions in 2019 and 2023.",
    fact: "Stadium 974 in Doha was built from exactly 974 shipping containers — then dismantled.",
    status: "🟥 ELIMINATED IN GROUP B."
  },
  sui: {
    name: "SWITZERLAND", flag: "🇨🇭", group: "B", lat: 46.8, lon: 8.2,
    tagline: "LA NATI",
    kit: { p: "#DA291C", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#DA291C" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🏔", "🧀", "🍫", "⌚"] },
    knownFor: "Alpine peaks, precision watches, chocolate, fondue — and a national team that quietly beats giants (ask France, 2021).",
    sights: ["The Matterhorn, Zermatt", "Lake Geneva & Chillon Castle", "Lucerne's Chapel Bridge"],
    foods: ["Cheese fondue & raclette", "Swiss chocolate", "Rösti"],
    culture: "Four national languages, yodeling and alphorns in the valleys, banking towers in Zurich, direct democracy by referendum.",
    legends: ["Granit Xhaka", "Xherdan Shaqiri", "Yann Sommer", "Breel Embolo"],
    wc: "13th appearance. Quarterfinalists in 1934, 1938 and 1954 (as hosts) — chasing that mark again.",
    fact: "Switzerland has been officially neutral since 1815 — except on matchday.",
    status: "🟦 WON GROUP B (7 PTS) → BEAT ALGERIA 2-0 → FACES COLOMBIA IN THE ROUND OF 16, JUL 7."
  },

  /* ---------------- GROUP C ---------------- */
  bra: {
    name: "BRAZIL", flag: "🇧🇷", group: "C", lat: -10.8, lon: -52.9,
    tagline: "A SELEÇÃO — 5× CHAMPIONS",
    kit: { p: "#FFDC00", s: "#009C3B", pattern: "solid", shorts: "#002776", socks: "#FFFFFF" },
    bg: { g1: "#052e16", g2: "#16a34a", motifs: ["🌴", "🥁", "🦜", "⚽"] },
    knownFor: "Jogo bonito — the beautiful game. Carnival, samba, Copacabana, the Amazon, and more World Cups (5) than any nation on Earth.",
    sights: ["Christ the Redeemer, Rio", "Iguazu Falls", "Amazon rainforest cruises"],
    foods: ["Feijoada (black bean stew)", "Pão de queijo", "Brigadeiro & caipirinha"],
    culture: "Samba schools rehearse all year for Carnival; futevôlei on the beach, capoeira circles, and football as religion.",
    legends: ["Pelé", "Ronaldo", "Ronaldinho", "Neymar", "Vinícius Jr."],
    wc: "23rd appearance — the only nation to play in every World Cup. Champions in 1958, '62, '70, '94, 2002.",
    fact: "Pelé remains the only player to win three World Cups (1958, 1962, 1970).",
    status: "🟨 WON GROUP C (7 PTS) → BEAT JAPAN 2-1 → STUNNED BY NORWAY & A HAALAND BRACE IN THE ROUND OF 16."
  },
  mar: {
    name: "MOROCCO", flag: "🇲🇦", group: "C", lat: 31.8, lon: -6.1,
    tagline: "ATLAS LIONS",
    kit: { p: "#C1272D", s: "#006233", pattern: "solid", shorts: "#006233", socks: "#C1272D" },
    bg: { g1: "#1c0b06", g2: "#a3512b", motifs: ["🕌", "🐫", "🍊", "🏜"] },
    knownFor: "Marrakech's souks, Saharan dunes, mint tea — and the 2022 semifinal run that made them Africa's team. Now they're even better.",
    sights: ["Jemaa el-Fnaa, Marrakech", "Chefchaouen — the blue city", "Sahara camps at Merzouga"],
    foods: ["Tagine", "Couscous (Friday tradition)", "Mint tea & pastilla"],
    culture: "Amazigh (Berber), Arab and Andalusian threads woven into riads, gnawa music and hammam ritual.",
    legends: ["Achraf Hakimi", "Yassine Bounou", "Brahim Díaz", "Mustapha Hadji"],
    wc: "7th appearance. First African semifinalist ever (2022) — and 2030 co-hosts.",
    fact: "Morocco's 2022 run beat Belgium, Spain AND Portugal without conceding to an opponent.",
    status: "🟦 RUNNER-UP GROUP C (7 PTS) → BEAT NETHERLANDS ON PENALTIES → CRUSHED CANADA 3-0 → QUARTERFINAL VS FRANCE, JUL 9."
  },
  hai: {
    name: "HAITI", flag: "🇭🇹", group: "C", lat: 19.0, lon: -72.3,
    tagline: "LES GRENADIERS",
    kit: { p: "#00209F", s: "#D21034", pattern: "halves", shorts: "#00209F", socks: "#D21034" },
    bg: { g1: "#0a1030", g2: "#25368f", motifs: ["🏝", "🥁", "🎨", "🌺"] },
    knownFor: "The first Black republic in history, kompa music, vivid street art — and a fairytale return to the World Cup after 52 years.",
    sights: ["Citadelle Laferrière fortress", "Labadee coast", "Bassin Bleu waterfalls"],
    foods: ["Griot (fried pork)", "Diri ak djon djon (black mushroom rice)", "Soup joumou"],
    culture: "Vodou drumming, RaRa street parades, naïve-art masters and Creole storytelling born of revolution.",
    legends: ["Emmanuel Sanon", "Duckens Nazon", "Danley Jean Jacques"],
    wc: "2nd appearance — first since 1974, when Sanon famously beat Dino Zoff's 1,142-minute clean-sheet run.",
    fact: "Soup joumou, eaten every Jan 1, celebrates independence — it was once forbidden to the enslaved.",
    status: "🟥 ELIMINATED IN GROUP C — BUT THE RETURN AFTER 52 YEARS WAS THE STORY."
  },
  sco: {
    name: "SCOTLAND", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", group: "C", lat: 56.5, lon: -4.2,
    tagline: "THE TARTAN ARMY",
    kit: { p: "#003078", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#003078" },
    bg: { g1: "#0a1226", g2: "#274b8f", motifs: ["🏰", "🎻", "🦌", "🌧"] },
    knownFor: "Highlands and lochs, bagpipes, kilts, whisky — and the Tartan Army, football's friendliest travelling invasion.",
    sights: ["Edinburgh Castle & the Royal Mile", "Loch Ness", "Isle of Skye"],
    foods: ["Haggis, neeps & tatties", "Scotch whisky", "Cullen skink"],
    culture: "Clan tartans, Highland games, ceilidh dancing and poetry nights for Robert Burns.",
    legends: ["Kenny Dalglish", "Denis Law", "Andy Robertson", "John McGinn"],
    wc: "9th appearance — first since 1998, ending the longest wait of any returning European side.",
    fact: "Scotland and England played the world's first international match in 1872. It was 0-0.",
    status: "🟥 ELIMINATED IN GROUP C — THE TARTAN ARMY WON THE PARTY ANYWAY."
  },

  /* ---------------- GROUP D ---------------- */
  usa: {
    name: "UNITED STATES", flag: "🇺🇸", group: "D", lat: 39.8, lon: -98.6,
    tagline: "THE STARS & STRIPES — HOST NATION",
    kit: { p: "#FFFFFF", s: "#B22234", pattern: "solid", shorts: "#3C3B6E", socks: "#FFFFFF" },
    bg: { g1: "#0a1030", g2: "#3c3b6e", motifs: ["🗽", "🦅", "🏟", "🎆"] },
    knownFor: "Skylines, national parks, Hollywood and hip-hop — and a soccer boom peaking at exactly the right time: a home World Cup.",
    sights: ["Statue of Liberty, NYC", "Grand Canyon", "Golden Gate Bridge"],
    foods: ["Smash burgers", "Texas BBQ brisket", "Apple pie"],
    culture: "Fifty states of road-trip Americana: college marching bands, diners, tailgates — now with soccer chants in every accent.",
    legends: ["Christian Pulisic", "Landon Donovan", "Tim Howard", "Clint Dempsey"],
    wc: "12th appearance. Semifinalists at the very first Cup (1930); hosts in 1994 and 2026.",
    fact: "The 1994 USA World Cup still holds the all-time attendance record — until this one likely breaks it.",
    status: "🟦 WON GROUP D (6 PTS) → BEAT BOSNIA 2-0 → FACES BELGIUM TONIGHT IN SEATTLE — LAST HOST STANDING!"
  },
  par: {
    name: "PARAGUAY", flag: "🇵🇾", group: "D", lat: -23.4, lon: -58.4,
    tagline: "LA ALBIRROJA",
    kit: { p: "#D52B1E", s: "#FFFFFF", pattern: "stripes", shorts: "#0038A8", socks: "#0038A8" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🧉", "🌊", "🎸", "🏞"] },
    knownFor: "Tereré (iced yerba mate) shared everywhere, Guaraní — the only indigenous language co-official nationwide — and giant-killing grit.",
    sights: ["Itaipú Dam (world's 2nd-largest)", "Asunción's Costanera", "Jesuit ruins of Trinidad"],
    foods: ["Chipa (cheese bread)", "Sopa paraguaya (a 'soup' that's solid)", "Asado"],
    culture: "Ñandutí lace, polka paraguaya on the harp, and mate rounds that pause the whole afternoon.",
    legends: ["José Luis Chilavert", "Roque Santa Cruz", "Miguel Almirón", "Julio Enciso"],
    wc: "9th appearance. Quarterfinalists in 2010 — and 2026 authors of the tournament's biggest upset.",
    fact: "Paraguay declared a national holiday after knocking out Germany in the Round of 32.",
    status: "🟨 ADVANCED FROM GROUP D AS A BEST 3RD → SHOCKED GERMANY IN THE R32 (NATIONAL HOLIDAY!) → FELL 1-0 TO FRANCE IN THE ROUND OF 16."
  },
  aus: {
    name: "AUSTRALIA", flag: "🇦🇺", group: "D", lat: -25.3, lon: 133.8,
    tagline: "THE SOCCEROOS",
    kit: { p: "#FFB81C", s: "#00843D", pattern: "solid", shorts: "#00843D", socks: "#FFB81C" },
    bg: { g1: "#1c1206", g2: "#a3752b", motifs: ["🦘", "🏄", "🐨", "🌞"] },
    knownFor: "Beaches, reefs and outback red dirt; kangaroos outnumber people — and the Socceroos never, ever stop running.",
    sights: ["Sydney Opera House & Harbour", "Great Barrier Reef", "Uluru"],
    foods: ["Meat pie at the footy", "Vegemite toast", "Lamingtons & flat whites"],
    culture: "60,000+ years of First Nations heritage, surf-lifesaving clubs, backyard cricket and a sports-mad public.",
    legends: ["Tim Cahill", "Harry Kewell", "Mat Ryan", "Jackson Irvine"],
    wc: "7th appearance — 6th in a row. Round of 16 in 2006 and 2022.",
    fact: "Australia once won a qualifier 31-0 (vs American Samoa, 2001) — a world record.",
    status: "🟩 RUNNER-UP GROUP D → OUT ON PENALTIES (2-4) VS EGYPT IN THE ROUND OF 32."
  },
  tur: {
    name: "TÜRKIYE", flag: "🇹🇷", group: "D", lat: 39.0, lon: 35.2,
    tagline: "AY-YILDIZLILAR (THE CRESCENT-STARS)",
    kit: { p: "#E30A17", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#E30A17" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🕌", "🎈", "☕", "🌉"] },
    knownFor: "Istanbul straddling two continents, Cappadocia's balloon skies, çay in tulip glasses and the loudest ultras in Europe.",
    sights: ["Hagia Sophia & the Blue Mosque", "Cappadocia balloon fields", "Pamukkale terraces"],
    foods: ["Kebap & lahmacun", "Baklava", "Turkish breakfast spreads"],
    culture: "Ottoman calligraphy, whirling dervishes, grand bazaars and tea offered before any conversation.",
    legends: ["Hakan Şükür", "Arda Güler", "Hakan Çalhanoğlu", "Rüştü Reçber"],
    wc: "3rd appearance. Third place in 2002 — Şükür's 10.8-second goal is still the fastest in World Cup history.",
    fact: "Istanbul's Grand Bazaar has 4,000 shops across 61 covered streets.",
    status: "🟥 ELIMINATED IN GROUP D."
  },

  /* ---------------- GROUP E ---------------- */
  ger: {
    name: "GERMANY", flag: "🇩🇪", group: "E", lat: 51.2, lon: 10.4,
    tagline: "DIE MANNSCHAFT — 4× CHAMPIONS",
    kit: { p: "#FFFFFF", s: "#000000", pattern: "solid", shorts: "#000000", socks: "#FFFFFF" },
    bg: { g1: "#111111", g2: "#3d3d3d", motifs: ["🏰", "🍺", "🥨", "🚗"] },
    knownFor: "Autobahns, Oktoberfest, fairy-tale castles, engineering — and tournament football so reliable they invented the word 'Turniermannschaft'. Until now.",
    sights: ["Brandenburg Gate, Berlin", "Neuschwanstein Castle", "Cologne Cathedral"],
    foods: ["Bratwurst & currywurst", "Pretzels & sauerkraut", "Black Forest cake"],
    culture: "Beer gardens under chestnut trees, Bauhaus design, techno in Berlin bunkers and Christmas markets everywhere.",
    legends: ["Franz Beckenbauer", "Gerd Müller", "Miroslav Klose", "Jamal Musiala"],
    wc: "21st appearance. Champions 1954, '74, '90, 2014; Klose is the Cup's all-time top scorer (16).",
    fact: "Germany has played more World Cup matches than any other nation.",
    status: "🟩 ADVANCED FROM GROUP E → SENSATIONALLY UPSET BY PARAGUAY IN THE ROUND OF 32."
  },
  cuw: {
    name: "CURAÇAO", flag: "🇨🇼", group: "E", lat: 12.2, lon: -69.0,
    tagline: "THE BLUE WAVE — SMALLEST EVER QUALIFIER",
    kit: { p: "#002B7F", s: "#F9E814", pattern: "solid", shorts: "#FFFFFF", socks: "#002B7F" },
    bg: { g1: "#061a30", g2: "#1e6db0", motifs: ["🏝", "🎨", "🐠", "🍹"] },
    knownFor: "Rainbow-painted Willemstad, turquoise coves, and the smallest nation (about 150k people) ever to reach a World Cup.",
    sights: ["Handelskade waterfront, Willemstad", "Klein Curaçao islet", "Shete Boka national park"],
    foods: ["Keshi yená (stuffed cheese)", "Fresh iguana soup (yes, really)", "Batido smoothies"],
    culture: "Papiamentu language, tumba carnival rhythms and Dutch-Caribbean gabled houses in ice-cream colours.",
    legends: ["Leandro Bacuna", "Eloy Room", "Tahith Chong"],
    wc: "1st appearance — a record-smashing debut for the tiny island.",
    fact: "Curaçao overtook Iceland (2018) as the least-populous World Cup nation in history.",
    status: "🟥 ELIMINATED IN GROUP E — BUT FOREVER IN THE RECORD BOOKS."
  },
  ecu: {
    name: "ECUADOR", flag: "🇪🇨", group: "E", lat: -1.8, lon: -78.2,
    tagline: "LA TRI",
    kit: { p: "#FFDD00", s: "#034EA2", pattern: "solid", shorts: "#034EA2", socks: "#EF3340" },
    bg: { g1: "#1c1206", g2: "#a3752b", motifs: ["🌋", "🐢", "🍌", "⛰"] },
    knownFor: "The middle of the world — the Equator line, Galápagos wildlife, Andean volcanoes and a conveyor belt of fearless young talent.",
    sights: ["Galápagos Islands", "Quito's colonial old town", "Cotopaxi volcano"],
    foods: ["Ceviche ecuatoriano", "Llapingachos (potato cakes)", "Encebollado fish stew"],
    culture: "Kichwa markets in Otavalo, panama hats (born in Ecuador!), and altitude football at 2,850m.",
    legends: ["Agustín Delgado", "Antonio Valencia", "Moisés Caicedo", "Kendry Páez"],
    wc: "5th appearance. Round of 16 in 2006.",
    fact: "Quito is the world's second-highest capital — visiting teams gasp at 2,850 m.",
    status: "🟩 ADVANCED FROM GROUP E → ELIMINATED BY HOSTS MEXICO IN THE ROUND OF 32."
  },
  civ: {
    name: "IVORY COAST", flag: "🇨🇮", group: "E", lat: 7.5, lon: -5.5,
    tagline: "LES ÉLÉPHANTS",
    kit: { p: "#FF8200", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#009A44" },
    bg: { g1: "#1c1206", g2: "#c96f1e", motifs: ["🐘", "🥁", "🌴", "☕"] },
    knownFor: "The world's cocoa capital, reigning African champions' pedigree, beach breaks at Assinie and the legacy of Drogba.",
    sights: ["Basilica of Yamoussoukro (world's largest church)", "Abidjan's lagoon skyline", "Taï National Forest"],
    foods: ["Attiéké with grilled fish", "Alloco (fried plantain)", "Garba"],
    culture: "Zouglou and coupé-décalé music, mask traditions of the Dan people, and football that stopped a civil war (Drogba, 2005).",
    legends: ["Didier Drogba", "Yaya Touré", "Sébastien Haller", "Simon Adingra"],
    wc: "4th appearance. AFCON champions 2015 and 2024.",
    fact: "Ivory Coast grows ~40% of the world's cocoa. Your chocolate probably started here.",
    status: "🟩 ADVANCED FROM GROUP E → OUT TO A LATE HAALAND WINNER IN THE ROUND OF 32."
  },

  /* ---------------- GROUP F ---------------- */
  ned: {
    name: "NETHERLANDS", flag: "🇳🇱", group: "F", lat: 52.2, lon: 5.3,
    tagline: "ORANJE",
    kit: { p: "#FF6600", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#FF6600" },
    bg: { g1: "#1c0f06", g2: "#c9601e", motifs: ["🌷", "🚲", "🧀", "🌬"] },
    knownFor: "Total Football's birthplace: canals, bikes, tulips, windmills — and the eternal ache of three lost finals.",
    sights: ["Amsterdam's canal ring", "Keukenhof tulip gardens", "Kinderdijk windmills"],
    foods: ["Stroopwafels", "Bitterballen", "Gouda & herring stands"],
    culture: "Cycling as a way of life, Van Gogh and Vermeer, King's Day when the whole country dresses orange.",
    legends: ["Johan Cruyff", "Marco van Basten", "Virgil van Dijk", "Cody Gakpo"],
    wc: "12th appearance. Runners-up 1974, 1978, 2010 — the best team never to win it.",
    fact: "There are more bikes than people in the Netherlands (~23M bikes, 18M people).",
    status: "🟩 ADVANCED FROM GROUP F → OUT ON PENALTIES TO MOROCCO IN A WILD ROUND OF 32."
  },
  jpn: {
    name: "JAPAN", flag: "🇯🇵", group: "F", lat: 36.2, lon: 138.3,
    tagline: "SAMURAI BLUE",
    kit: { p: "#003DA5", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#003DA5" },
    bg: { g1: "#0a1030", g2: "#25368f", motifs: ["🗻", "🌸", "🏮", "🎌"] },
    knownFor: "Shinkansen precision, anime and manga, cherry blossoms, temple gardens — and fans who clean the stadium after every match.",
    sights: ["Mount Fuji", "Kyoto's Fushimi Inari gates", "Tokyo's Shibuya Crossing"],
    foods: ["Sushi & ramen", "Okonomiyaki", "Matcha everything"],
    culture: "Tea ceremony and taiko drums beside robot cafés; 'Captain Tsubasa' made a whole generation fall for football.",
    legends: ["Hidetoshi Nakata", "Keisuke Honda", "Takefusa Kubo", "Kaoru Mitoma"],
    wc: "8th straight appearance. Beat Germany AND Spain in 2022.",
    fact: "Japanese fans' post-match stadium cleanup went viral at three straight World Cups.",
    status: "🟩 ADVANCED FROM GROUP F → FELL 2-1 TO BRAZIL IN THE ROUND OF 32."
  },
  swe: {
    name: "SWEDEN", flag: "🇸🇪", group: "F", lat: 62.0, lon: 15.0,
    tagline: "BLÅGULT (BLUE-YELLOW)",
    kit: { p: "#FFCD00", s: "#004B87", pattern: "solid", shorts: "#004B87", socks: "#FFCD00" },
    bg: { g1: "#0d1526", g2: "#31456e", motifs: ["🌲", "❄️", "🛶", "🫎"] },
    knownFor: "Midnight sun, ABBA, fika coffee breaks, flat-pack furniture — and strikers: from Zlatan to a new golden crop.",
    sights: ["Stockholm's Gamla Stan", "Icehotel in Jukkasjärvi", "Gothenburg archipelago"],
    foods: ["Meatballs with lingonberries", "Cinnamon buns (fika!)", "Gravlax"],
    culture: "Lagom (just-enough) living, Midsummer maypoles, allemansrätten — the right to roam any forest.",
    legends: ["Zlatan Ibrahimović", "Henrik Larsson", "Viktor Gyökeres", "Alexander Isak"],
    wc: "13th appearance. Runners-up at home in 1958 — to 17-year-old Pelé's Brazil.",
    fact: "Swedish has no exact word for 'please', but fika (coffee + bun + pause) is sacred.",
    status: "🟩 ADVANCED FROM GROUP F → BLANKED 3-0 BY FRANCE IN THE ROUND OF 32."
  },
  tun: {
    name: "TUNISIA", flag: "🇹🇳", group: "F", lat: 34.0, lon: 9.5,
    tagline: "EAGLES OF CARTHAGE",
    kit: { p: "#E70013", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#E70013" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🏛", "🏜", "🫒", "🌊"] },
    knownFor: "Carthaginian ruins, Star Wars desert sets, Mediterranean beaches and harissa heat.",
    sights: ["Ruins of Carthage", "Sidi Bou Said blue-white village", "Amphitheatre of El Jem"],
    foods: ["Couscous with lamb", "Brik à l'oeuf", "Harissa on everything"],
    culture: "Medina souks, Andalusian malouf music and jasmine sellers at dusk.",
    legends: ["Tarak Dhiab", "Radhi Jaïdi", "Youssef Msakni", "Hannibal Mejbri"],
    wc: "7th appearance. First African side to win a World Cup match (1978, vs Mexico).",
    fact: "Luke Skywalker's home planet Tatooine is named after the real Tunisian town Tataouine.",
    status: "🟥 ELIMINATED IN GROUP F."
  },

  /* ---------------- GROUP G ---------------- */
  bel: {
    name: "BELGIUM", flag: "🇧🇪", group: "G", lat: 50.6, lon: 4.5,
    tagline: "THE RED DEVILS",
    kit: { p: "#E30613", s: "#000000", pattern: "solid", shorts: "#000000", socks: "#E30613" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🍟", "🍫", "🏰", "🎨"] },
    knownFor: "Waffles, 1,500+ beers, comic-strip murals, EU headquarters — and a new generation chasing what the 'golden generation' never caught.",
    sights: ["Grand Place, Brussels", "Bruges' canals", "Atomium"],
    foods: ["Frites with andalouse sauce", "Belgian waffles", "Moules-frites & trappist beer"],
    culture: "Tintin and the Smurfs were born here; three official languages argue about everything except football.",
    legends: ["Kevin De Bruyne", "Eden Hazard", "Thibaut Courtois", "Jérémy Doku"],
    wc: "15th appearance. Third place in 2018; No. 1 in the world for years without a trophy — yet.",
    fact: "Fries were (Belgians insist) invented in Belgium, not France. Fighting words.",
    status: "🟦 ADVANCED FROM GROUP G → OUTLASTED SENEGAL 3-2 AET → FACES THE USA TONIGHT IN SEATTLE."
  },
  egy: {
    name: "EGYPT", flag: "🇪🇬", group: "G", lat: 26.8, lon: 30.0,
    tagline: "THE PHARAOHS",
    kit: { p: "#CE1126", s: "#FFFFFF", pattern: "solid", shorts: "#000000", socks: "#CE1126" },
    bg: { g1: "#1c1206", g2: "#a3752b", motifs: ["🐪", "🏜", "𓂀", "⛵"] },
    knownFor: "Five thousand years of pyramids and pharaohs, the Nile, Cairo's chaos and charm — and Mo Salah's last great quest.",
    sights: ["Pyramids of Giza & the Sphinx", "Grand Egyptian Museum", "Luxor's Valley of the Kings"],
    foods: ["Koshari", "Ful medames", "Molokhia"],
    culture: "Call to prayer over Cairo's rooftops, felucca sails on the Nile, café backgammon and Umm Kulthum on the radio.",
    legends: ["Mohamed Salah", "Mohamed Aboutrika", "Essam El-Hadary", "Omar Marmoush"],
    wc: "4th appearance. Africa's first-ever World Cup side (1934); record 7× African champions.",
    fact: "Essam El-Hadary kept goal at a World Cup aged 45 — the oldest player ever.",
    status: "🟦 ADVANCED FROM GROUP G → BEAT AUSTRALIA ON PENALTIES → SALAH VS MESSI: ARGENTINA AWAITS, JUL 7."
  },
  irn: {
    name: "IRAN", flag: "🇮🇷", group: "G", lat: 32.0, lon: 53.7,
    tagline: "TEAM MELLI",
    kit: { p: "#FFFFFF", s: "#DA0000", pattern: "solid", shorts: "#FFFFFF", socks: "#239F40" },
    bg: { g1: "#0d1a12", g2: "#2e6e45", motifs: ["🕌", "🏔", "🌹", "🐆"] },
    knownFor: "Persian poetry and gardens, dazzling tile-work mosques, saffron and 2,500 years of empire history.",
    sights: ["Naqsh-e Jahan Square, Isfahan", "Persepolis", "Shiraz's Pink Mosque"],
    foods: ["Chelo kabab", "Ghormeh sabzi", "Saffron ice cream (bastani)"],
    culture: "Hafez poems recited by heart, Persian rugs woven over months, Nowruz new year at the spring equinox.",
    legends: ["Ali Daei", "Mehdi Taremi", "Sardar Azmoun", "Ali Karimi"],
    wc: "7th appearance — Asia's most passionate 100,000-seat home crowds at Azadi Stadium.",
    fact: "Ali Daei was the first man to score 100 international goals — later passed only by Ronaldo & Messi.",
    status: "🟥 ELIMINATED IN GROUP G."
  },
  nzl: {
    name: "NEW ZEALAND", flag: "🇳🇿", group: "G", lat: -41.5, lon: 173.5,
    tagline: "THE ALL WHITES",
    kit: { p: "#FFFFFF", s: "#000000", pattern: "solid", shorts: "#FFFFFF", socks: "#FFFFFF" },
    bg: { g1: "#0d1526", g2: "#31456e", motifs: ["🥝", "🏔", "🐑", "🌿"] },
    knownFor: "Middle-earth landscapes, Māori haka, adventure sports capital Queenstown — and sheep outnumbering people 5 to 1.",
    sights: ["Milford Sound", "Hobbiton, Matamata", "Rotorua geothermal parks"],
    foods: ["Hāngī earth-oven feast", "Pavlova (sorry, Australia)", "Green-lipped mussels"],
    culture: "Māori carving and haka, rugby religion, 'she'll be right' calm and DIY spirit.",
    legends: ["Wynton Rufer", "Chris Wood", "Ryan Nelsen"],
    wc: "3rd appearance. Went unbeaten (3 draws) in 2010 — the only undefeated team that year.",
    fact: "NZ named its football team the All Whites to rhyme with rugby's All Blacks.",
    status: "🟥 ELIMINATED IN GROUP G."
  },

  /* ---------------- GROUP H ---------------- */
  esp: {
    name: "SPAIN", flag: "🇪🇸", group: "H", lat: 40.2, lon: -3.9,
    tagline: "LA ROJA — EURO 2024 CHAMPIONS",
    kit: { p: "#AA151B", s: "#F1BF00", pattern: "solid", shorts: "#000C8A", socks: "#AA151B" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["💃", "🥘", "🏰", "☀️"] },
    knownFor: "Tiki-taka reborn: flamenco, tapas crawls, Gaudí's Barcelona, siestas and fiestas — and the world's best young winger, Lamine Yamal.",
    sights: ["Sagrada Família, Barcelona", "Alhambra, Granada", "Plaza Mayor & Prado, Madrid"],
    foods: ["Paella valenciana", "Jamón ibérico", "Churros con chocolate"],
    culture: "Flamenco duende, La Tomatina food fights, midnight dinners and football debated like philosophy.",
    legends: ["Andrés Iniesta", "Xavi", "Iker Casillas", "Lamine Yamal", "Pedri"],
    wc: "17th appearance. Champions 2010; European champions 2024 playing the tournament's prettiest football.",
    fact: "Lamine Yamal became Spain's youngest ever World Cup scorer this summer — still a teenager.",
    status: "🟦 WON GROUP H → CRUISED PAST AUSTRIA (OYARZABAL ×2) → MERINO'S 90+1' WINNER BEAT PORTUGAL 1-0 → QUARTERFINAL VS USA/BELGIUM, JUL 10 IN LA."
  },
  cpv: {
    name: "CAPE VERDE", flag: "🇨🇻", group: "H", lat: 15.1, lon: -23.6,
    tagline: "THE BLUE SHARKS",
    kit: { p: "#003893", s: "#CF2027", pattern: "solid", shorts: "#FFFFFF", socks: "#003893" },
    bg: { g1: "#061a30", g2: "#1e6db0", motifs: ["🌊", "🎶", "🦈", "🏝"] },
    knownFor: "Ten Atlantic islands of morna music and beach volcanoes; half a million people and a diaspora twice that size — all singing at this World Cup.",
    sights: ["Fogo volcano crater villages", "Sal's white beaches", "Cidade Velha (UNESCO)"],
    foods: ["Cachupa (slow stew)", "Fresh tuna & wahoo", "Grogue rum & pastel"],
    culture: "Cesária Évora's morna made the islands famous; Creole culture blends West Africa and Portugal.",
    legends: ["Ryan Mendes", "Bebé", "Jamiro Monteiro"],
    wc: "1st appearance — and they took defending champions Argentina to extra time in the knockouts.",
    fact: "Cape Verde's World Cup debut squad drew players born in 7 different countries.",
    status: "🟩 ADVANCED FROM GROUP H → HEARTBREAK: 3-2 AET LOSS TO ARGENTINA AFTER LEADING THE CHAMPS."
  },
  ksa: {
    name: "SAUDI ARABIA", flag: "🇸🇦", group: "H", lat: 24.0, lon: 45.0,
    tagline: "THE GREEN FALCONS",
    kit: { p: "#006C35", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#006C35" },
    bg: { g1: "#0d1a12", g2: "#2e6e45", motifs: ["🕋", "🏜", "🐪", "🌴"] },
    knownFor: "Mecca and Medina, Nabatean rock cities, mega-projects rising from the desert — and the 2022 win over eventual champions Argentina.",
    sights: ["Hegra (Madain Salih), AlUla", "Edge of the World cliffs", "Jeddah's old town Al-Balad"],
    foods: ["Kabsa", "Dates & Arabic coffee", "Mutabbaq"],
    culture: "Bedouin poetry, falconry, camel fairs and Ardah sword dance; hosts of the 2034 World Cup.",
    legends: ["Majed Abdullah", "Sami Al-Jaber", "Salem Al-Dawsari"],
    wc: "7th appearance. That 2-1 over Argentina in 2022 triggered a national holiday.",
    fact: "Saudi Arabia is the largest country in the world with no rivers.",
    status: "🟥 ELIMINATED IN GROUP H."
  },
  uru: {
    name: "URUGUAY", flag: "🇺🇾", group: "H", lat: -32.8, lon: -56.0,
    tagline: "LA CELESTE — 2× CHAMPIONS",
    kit: { p: "#55B5E5", s: "#FFFFFF", pattern: "solid", shorts: "#000000", socks: "#55B5E5" },
    bg: { g1: "#061a30", g2: "#1e6db0", motifs: ["🧉", "🥩", "🌅", "⭐"] },
    knownFor: "The first World Cup hosts and champions (1930); mate thermoses under every arm, asado smoke, and 'garra charrúa' fighting spirit.",
    sights: ["Punta del Este beaches", "Colonia del Sacramento", "Montevideo's Rambla"],
    foods: ["Asado & chivito", "Mate (national ritual)", "Dulce de leche alfajores"],
    culture: "Candombe drums in Barrio Sur, tango shared with Argentina, and a 3.4M-person nation with four stars on its crest.",
    legends: ["Diego Forlán", "Luis Suárez", "Edinson Cavani", "Federico Valverde"],
    wc: "15th appearance. Champions 1930 & 1950 — the 'Maracanazo' silencing 200,000 Brazilians.",
    fact: "Uruguay's Estadio Centenario hosted the first-ever World Cup final in 1930.",
    status: "🟥 SHOCK OF THE GROUPS — ELIMINATED IN GROUP H."
  },

  /* ---------------- GROUP I ---------------- */
  fra: {
    name: "FRANCE", flag: "🇫🇷", group: "I", lat: 46.6, lon: 2.5,
    tagline: "LES BLEUS — TOURNAMENT FAVORITES",
    kit: { p: "#001E62", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#ED2939" },
    bg: { g1: "#0a1030", g2: "#25368f", motifs: ["🗼", "🥐", "🍷", "🎨"] },
    knownFor: "The Eiffel Tower, the Louvre, café terraces and haute cuisine — and Mbappé's Bleus, who haven't conceded a knockout goal yet.",
    sights: ["Eiffel Tower & the Seine", "Palace of Versailles", "Mont-Saint-Michel"],
    foods: ["Croissants & baguettes", "Coq au vin", "300+ cheeses"],
    culture: "Impressionist light, Bastille Day fireworks, Tour de France summers and l'art de vivre.",
    legends: ["Zinedine Zidane", "Kylian Mbappé", "Michel Platini", "Thierry Henry", "Antoine Griezmann"],
    wc: "17th appearance. Champions 1998 & 2018, runners-up 2022 — in a third straight final hunt.",
    fact: "Mbappé scored a hat-trick in the 2022 final and still lost. He remembers.",
    status: "🟦 WON GROUP I → CRUSHED SWEDEN 3-0 → EDGED PARAGUAY 1-0 → QUARTERFINAL VS MOROCCO IN BOSTON, JUL 9. FAVORITES AT +170."
  },
  sen: {
    name: "SENEGAL", flag: "🇸🇳", group: "I", lat: 14.5, lon: -14.5,
    tagline: "LIONS OF TERANGA",
    kit: { p: "#FFFFFF", s: "#00853F", pattern: "solid", shorts: "#00853F", socks: "#FDEF42" },
    bg: { g1: "#0d1a12", g2: "#2e6e45", motifs: ["🦁", "🥁", "🌊", "🎣"] },
    knownFor: "Teranga (hospitality), Dakar's surf and sabar drums, the pink lake — and Africa's most consistently fearsome team.",
    sights: ["Gorée Island memorial", "Lake Retba (the Pink Lake)", "Dakar's Cap Manuel cliffs"],
    foods: ["Thieboudienne (fish & rice)", "Yassa chicken", "Bissap juice"],
    culture: "Mbalax rhythm kings like Youssou N'Dour, Senegalese wrestling (làmb) packing stadiums, boubou fashion.",
    legends: ["Sadio Mané", "El Hadji Diouf", "Kalidou Koulibaly", "Iliman Ndiaye"],
    wc: "4th appearance. Quarterfinalists on debut in 2002, beating champions France en route.",
    fact: "Dakar's Monument of African Renaissance is taller than the Statue of Liberty.",
    status: "🟩 ADVANCED FROM GROUP I → FELL 3-2 IN EXTRA TIME TO BELGIUM — MATCH OF THE ROUND OF 32."
  },
  irq: {
    name: "IRAQ", flag: "🇮🇶", group: "I", lat: 33.2, lon: 43.7,
    tagline: "LIONS OF MESOPOTAMIA",
    kit: { p: "#007A3D", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#007A3D" },
    bg: { g1: "#0d1a12", g2: "#2e6e45", motifs: ["🏛", "🌴", "📜", "🕌"] },
    knownFor: "The cradle of civilization — Babylon, the Tigris and Euphrates, the birthplace of writing — back at the World Cup after 40 years.",
    sights: ["Ancient Babylon", "Erbil Citadel (7,000 years inhabited)", "The Mesopotamian Marshes"],
    foods: ["Masgouf (riverside grilled carp)", "Dolma", "Kleicha date cookies"],
    culture: "Poetry is a national sport; maqam music, tea houses on the Tigris, and the 2007 Asian Cup win that united a nation.",
    legends: ["Ahmed Radhi", "Younis Mahmoud", "Aymen Hussein"],
    wc: "2nd appearance — first since Mexico 1986.",
    fact: "Writing was invented in Iraq ~3200 BC. First thing written: probably a receipt.",
    status: "🟥 ELIMINATED IN GROUP I — BUT THE 40-YEAR RETURN MOVED THE WHOLE REGION."
  },
  nor: {
    name: "NORWAY", flag: "🇳🇴", group: "I", lat: 61.0, lon: 9.1,
    tagline: "THE HAALAND MACHINE",
    kit: { p: "#EF2B2D", s: "#FFFFFF", pattern: "solid", shorts: "#002868", socks: "#EF2B2D" },
    bg: { g1: "#0d1526", g2: "#31456e", motifs: ["⛰", "🚢", "❄️", "🌌"] },
    knownFor: "Fjords and northern lights, Viking longships, cross-country ski dominance — and Erling Haaland, the tournament's 7-goal wrecking ball.",
    sights: ["Geirangerfjord", "Lofoten Islands", "Oslo's Opera House rooftop"],
    foods: ["Salmon gravlaks", "Brunost (brown cheese)", "Kanelboller"],
    culture: "Friluftsliv (open-air life), Ibsen and Munch, cabins without wifi and total tournament fever right now.",
    legends: ["Erling Haaland", "Martin Ødegaard", "Ole Gunnar Solskjær"],
    wc: "4th appearance — first since 1998, and already their best ever after KO'ing Brazil.",
    fact: "Haaland's 7 goals lead the Golden Boot race — scored in just 5 matches.",
    status: "🟨 ADVANCED FROM GROUP I → SANK IVORY COAST → TOPPLED BRAZIL WITH A HAALAND BRACE → QUARTERFINAL VS ENGLAND IN MIAMI, JUL 11."
  },

  /* ---------------- GROUP J ---------------- */
  arg: {
    name: "ARGENTINA", flag: "🇦🇷", group: "J", lat: -34.6, lon: -64.0,
    tagline: "LA ALBICELESTE — DEFENDING CHAMPIONS",
    kit: { p: "#75AADB", s: "#FFFFFF", pattern: "stripes", shorts: "#000000", socks: "#FFFFFF" },
    bg: { g1: "#061a30", g2: "#1e6db0", motifs: ["⭐", "🥩", "💃", "🏔"] },
    knownFor: "Tango, asado, Patagonia — and the defense of the crown Messi finally lifted in 2022, in what may be his true final act.",
    sights: ["Perito Moreno Glacier", "Iguazú Falls", "La Boca's Caminito, Buenos Aires"],
    foods: ["Asado & chimichurri", "Empanadas", "Dulce de leche & Malbec"],
    culture: "Tango milongas at midnight, football as identity, Maradona murals as shrines and mate as friendship.",
    legends: ["Lionel Messi", "Diego Maradona", "Mario Kempes", "Gabriel Batistuta", "Julián Álvarez"],
    wc: "19th appearance. Champions 1978, 1986, 2022 — chasing back-to-back titles, last done by Brazil in 1962.",
    fact: "Messi, 39, is playing his SIXTH World Cup — a men's record.",
    status: "🟦 WON GROUP J → SURVIVED CAPE VERDE 3-2 AET → MESSI VS SALAH: EGYPT NEXT, JUL 7 IN ATLANTA. +470 SECOND-FAVORITES."
  },
  alg: {
    name: "ALGERIA", flag: "🇩🇿", group: "J", lat: 28.0, lon: 2.6,
    tagline: "THE FENNEC FOXES",
    kit: { p: "#FFFFFF", s: "#006233", pattern: "solid", shorts: "#FFFFFF", socks: "#006233" },
    bg: { g1: "#0d1a12", g2: "#2e6e45", motifs: ["🦊", "🏜", "🕌", "🌙"] },
    knownFor: "The Sahara's largest country, Casbah alleys of Algiers, raï music — and the fennec fox spirit: small, quick, impossible to catch.",
    sights: ["Casbah of Algiers", "Tassili n'Ajjer rock art", "Timgad Roman ruins"],
    foods: ["Couscous royale", "Chakhchoukha", "Makroud date pastries"],
    culture: "Raï legends like Cheb Khaled, Amazigh heritage in the Kabylie hills, café culture and fierce derby days.",
    legends: ["Riyad Mahrez", "Rabah Madjer", "Islam Slimani"],
    wc: "5th appearance. The 1982 win over West Germany is an all-time World Cup shock.",
    fact: "Madjer's 1987 back-heel for Porto is still called 'a Madjer' in Portuguese commentary.",
    status: "🟩 ADVANCED FROM GROUP J → BLANKED 2-0 BY SWITZERLAND IN THE ROUND OF 32."
  },
  aut: {
    name: "AUSTRIA", flag: "🇦🇹", group: "J", lat: 47.5, lon: 14.5,
    tagline: "DAS TEAM",
    kit: { p: "#ED2939", s: "#FFFFFF", pattern: "solid", shorts: "#FFFFFF", socks: "#ED2939" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🎼", "⛷", "🏔", "☕"] },
    knownFor: "Mozart and Vienna's coffee houses, Alpine ski resorts, Sound-of-Music scenery — and Ralf Rangnick's relentless pressing machine.",
    sights: ["Schönbrunn Palace, Vienna", "Hallstatt lakeside village", "Salzburg old town"],
    foods: ["Wiener schnitzel", "Sachertorte", "Apfelstrudel & melange coffee"],
    culture: "Waltzes at the Opera Ball, Christmas markets, cake-and-newspaper afternoons in grand cafés.",
    legends: ["Herbert Prohaska", "David Alaba", "Marcel Sabitzer", "Konrad Laimer"],
    wc: "8th appearance. Third place in 1954 — the 'Wunderteam' legacy lives on.",
    fact: "Vienna has been ranked the world's most liveable city more than any other.",
    status: "🟩 ADVANCED FROM GROUP J → OUT TO OYARZABAL'S DOUBLE VS SPAIN IN THE ROUND OF 32."
  },
  jor: {
    name: "JORDAN", flag: "🇯🇴", group: "J", lat: 31.2, lon: 36.5,
    tagline: "AL-NASHAMA (THE CHIVALROUS)",
    kit: { p: "#FFFFFF", s: "#CE1126", pattern: "solid", shorts: "#FFFFFF", socks: "#007A3D" },
    bg: { g1: "#1c0b06", g2: "#a3512b", motifs: ["🏛", "🏜", "🌹", "🐪"] },
    knownFor: "Petra's rose-red rock city, Wadi Rum's Mars-like desert, floating in the Dead Sea — a debutant nation the neutrals adopted.",
    sights: ["Petra's Treasury", "Wadi Rum", "The Dead Sea (lowest point on Earth)"],
    foods: ["Mansaf (lamb in jameed yogurt)", "Falafel & hummus", "Knafeh"],
    culture: "Bedouin tea by the fire, keffiyeh patterns, Roman ruins at Jerash and legendary hospitality.",
    legends: ["Musa Al-Taamari", "Yazan Al-Naimat", "Amer Shafi"],
    wc: "1st appearance — after reaching the 2023 Asian Cup final.",
    fact: "Petra was carved ~2,000 years ago and 'rediscovered' by the West only in 1812.",
    status: "🟥 ELIMINATED IN GROUP J — A PROUD DEBUT."
  },

  /* ---------------- GROUP K ---------------- */
  por: {
    name: "PORTUGAL", flag: "🇵🇹", group: "K", lat: 39.6, lon: -8.0,
    tagline: "A SELEÇÃO DAS QUINAS",
    kit: { p: "#E42518", s: "#006600", pattern: "solid", shorts: "#006600", socks: "#E42518" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["⛵", "🐟", "🎶", "🏰"] },
    knownFor: "Age-of-Discovery seafarers, azulejo tiles, fado's beautiful sadness, pastel de nata — and Cristiano Ronaldo's sixth and final World Cup.",
    sights: ["Belém Tower, Lisbon", "Porto's Ribeira & port cellars", "Sintra's Pena Palace"],
    foods: ["Pastéis de nata", "Bacalhau (365 recipes)", "Francesinha"],
    culture: "Fado in Alfama taverns, saudade as a national emotion, tiled facades and grilled sardine festivals.",
    legends: ["Cristiano Ronaldo", "Eusébio", "Luís Figo", "Bernardo Silva", "Rafael Leão"],
    wc: "9th appearance. Third in 1966 (Eusébio's 9 goals); Ronaldo, 41, chasing the one trophy left.",
    fact: "Ronaldo is the only man to score at SIX World Cups (2006–2026).",
    status: "🟥 RUNNER-UP GROUP K (5 PTS) → SURVIVED CROATIA IN VAR CHAOS → ELIMINATED 1-0 BY SPAIN IN THE R16. RONALDO'S SIXTH & FINAL WORLD CUP ENDS."
  },
  cod: {
    name: "DR CONGO", flag: "🇨🇩", group: "K", lat: -2.9, lon: 23.7,
    tagline: "THE LEOPARDS",
    kit: { p: "#007FFF", s: "#F7D618", pattern: "solid", shorts: "#CE1021", socks: "#007FFF" },
    bg: { g1: "#061a30", g2: "#1e6db0", motifs: ["🐆", "🌧", "🎷", "🦍"] },
    knownFor: "The mighty Congo River, rumba that made UNESCO's heritage list, sapeur fashion — back at the Cup for the first time since 1974 (as Zaire).",
    sights: ["Congo River rapids at Kinshasa", "Virunga National Park gorillas", "Mount Nyiragongo lava lake"],
    foods: ["Poulet à la moambe", "Fufu & pondu", "Grilled tilapia liboke"],
    culture: "Congolese rumba (Franco, Papa Wemba), the sapeurs' dandy elegance, and Kinshasa — the world's biggest French-speaking city.",
    legends: ["Cédric Bakambu", "Chancel Mbemba", "Yoane Wissa"],
    wc: "2nd appearance — first since Zaire 1974, Sub-Saharan Africa's original pioneers.",
    fact: "The Congo River is the world's deepest — over 220 m down in places.",
    status: "🟩 ADVANCED FROM GROUP K → OUT TO KANE'S LATE DOUBLE VS ENGLAND IN THE ROUND OF 32."
  },
  uzb: {
    name: "UZBEKISTAN", flag: "🇺🇿", group: "K", lat: 41.4, lon: 64.6,
    tagline: "THE WHITE WOLVES",
    kit: { p: "#FFFFFF", s: "#0099B5", pattern: "solid", shorts: "#0099B5", socks: "#FFFFFF" },
    bg: { g1: "#061a30", g2: "#1e6db0", motifs: ["🕌", "🐫", "🍉", "🧵"] },
    knownFor: "Silk Road jewel cities — Samarkand, Bukhara, Khiva — turquoise domes, plov feasts and a historic first World Cup.",
    sights: ["Registan Square, Samarkand", "Bukhara's old city", "Khiva's walled Itchan Kala"],
    foods: ["Plov (national obsession)", "Samsa", "Lagman noodles"],
    culture: "Caravanserai hospitality, suzani embroidery, chaikhana tea houses under mulberry trees.",
    legends: ["Eldor Shomurodov", "Abdukodir Khusanov", "Maksim Shatskikh"],
    wc: "1st appearance — Central Asia's first-ever World Cup nation.",
    fact: "Samarkand is over 2,750 years old — older than Rome.",
    status: "🟥 ELIMINATED IN GROUP K — HISTORY MADE ANYWAY."
  },
  col: {
    name: "COLOMBIA", flag: "🇨🇴", group: "K", lat: 4.6, lon: -74.1,
    tagline: "LOS CAFETEROS",
    kit: { p: "#FCD116", s: "#003893", pattern: "solid", shorts: "#003893", socks: "#CE1126" },
    bg: { g1: "#1c1206", g2: "#a3752b", motifs: ["☕", "💃", "🦋", "⛰"] },
    knownFor: "Coffee-farm valleys, Cartagena's walls, salsa capital Cali, Shakira and cumbia — and James Rodríguez conducting one last golden dance.",
    sights: ["Cartagena's old city", "Cocora Valley wax palms", "Medellín's comuna murals"],
    foods: ["Bandeja paisa", "Arepas", "Ajiaco & Colombian coffee"],
    culture: "Cumbia and vallenato, García Márquez's magical realism, flower festivals in Medellín.",
    legends: ["Carlos Valderrama", "James Rodríguez", "Falcao", "Luis Díaz"],
    wc: "7th appearance. James won the 2014 Golden Boot with THAT volley.",
    fact: "Colombia is the world's #1 source of emeralds and second-most biodiverse country.",
    status: "🟨 WON GROUP K (7 PTS) → EDGED GHANA 1-0 → FACES SWITZERLAND IN VANCOUVER, JUL 7."
  },

  /* ---------------- GROUP L ---------------- */
  eng: {
    name: "ENGLAND", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "L", lat: 52.5, lon: -1.5,
    tagline: "THE THREE LIONS",
    kit: { p: "#FFFFFF", s: "#001F44", pattern: "solid", shorts: "#001F44", socks: "#FFFFFF" },
    bg: { g1: "#0d1526", g2: "#31456e", motifs: ["👑", "☕", "🚌", "🦁"] },
    knownFor: "The birthplace of football, the Premier League, tea and queueing — plus Bellingham & Kane finally making 'It's Coming Home' sound serious.",
    sights: ["Big Ben & Westminster", "Tower of London", "Stonehenge"],
    foods: ["Fish & chips", "Sunday roast with Yorkshire puddings", "Full English breakfast"],
    culture: "Pub quizzes, terrace chants invented here, Shakespeare and the Beatles, tea solving every crisis.",
    legends: ["Harry Kane", "Jude Bellingham", "Bobby Moore", "Gary Lineker", "Bukayo Saka"],
    wc: "17th appearance. Champions 1966 at Wembley — the 60-year wait is the national obsession.",
    fact: "England invented the rules of football in a London pub in 1863 (The Freemasons' Tavern).",
    status: "🟦 WON GROUP L → KANE DOUBLE SANK DR CONGO → HELD OFF MEXICO 3-2 → QUARTERFINAL VS NORWAY IN MIAMI, JUL 11."
  },
  cro: {
    name: "CROATIA", flag: "🇭🇷", group: "L", lat: 45.2, lon: 15.5,
    tagline: "VATRENI (THE BLAZERS)",
    kit: { p: "#FFFFFF", s: "#FF0000", pattern: "checks", shorts: "#FFFFFF", socks: "#0093DD" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🏖", "🏰", "⛵", "🎭"] },
    knownFor: "The Adriatic's thousand islands, Dubrovnik's walls (King's Landing!), the iconic checkerboard kit — and a 4M-person nation that never stops overachieving.",
    sights: ["Dubrovnik old town", "Plitvice Lakes", "Diocletian's Palace, Split"],
    foods: ["Peka (slow-roasted under a bell)", "Black risotto", "Pag cheese & olive oil"],
    culture: "Klapa a-cappella by the sea, Roman amphitheatres hosting concerts, and the necktie — a Croatian invention (cravate).",
    legends: ["Luka Modrić", "Davor Šuker", "Ivan Rakitić", "Joško Gvardiol"],
    wc: "7th appearance. Finalists 2018, third 2022 — Modrić, 40, bowed out in the Round of 32.",
    fact: "The checkerboard comes from Croatia's coat of arms — šahovnica means 'chessboard'.",
    status: "🟩 ADVANCED FROM GROUP L → OUT IN VAR DRAMA VS PORTUGAL IN THE ROUND OF 32 — MODRIĆ'S FAREWELL."
  },
  gha: {
    name: "GHANA", flag: "🇬🇭", group: "L", lat: 7.9, lon: -1.0,
    tagline: "THE BLACK STARS",
    kit: { p: "#FFFFFF", s: "#000000", pattern: "solid", shorts: "#000000", socks: "#CE1126" },
    bg: { g1: "#1c1206", g2: "#a3752b", motifs: ["⭐", "🥁", "🏰", "🌊"] },
    knownFor: "The Black Star of Africa: highlife and afrobeats, kente cloth, Cape Coast history — and the 2010 quarterfinal that broke a continent's heart.",
    sights: ["Cape Coast Castle", "Kakum canopy walkway", "Lake Volta (world's largest reservoir)"],
    foods: ["Jollof rice (the best — don't @ Nigeria)", "Waakye", "Kelewele (spiced plantain)"],
    culture: "Adinkra symbols, talking drums, funerals celebrated as festivals of life, and fantasy coffins shaped like anything.",
    legends: ["Abedi Pelé", "Asamoah Gyan", "Michael Essien", "Mohammed Kudus"],
    wc: "5th appearance. One Suárez handball from a 2010 semifinal — Africa remembers.",
    fact: "Ghana was the first Sub-Saharan nation to gain independence (1957).",
    status: "🟩 ADVANCED FROM GROUP L → EDGED OUT 1-0 BY COLOMBIA IN THE ROUND OF 32."
  },
  pan: {
    name: "PANAMA", flag: "🇵🇦", group: "L", lat: 8.5, lon: -80.1,
    tagline: "LA MAREA ROJA (THE RED TIDE)",
    kit: { p: "#D21034", s: "#FFFFFF", pattern: "solid", shorts: "#00247D", socks: "#D21034" },
    bg: { g1: "#160b0b", g2: "#8f2f2a", motifs: ["🚢", "🌴", "🐸", "🎩"] },
    knownFor: "The canal that links two oceans, San Blas islands, reggaetón roots — and a football culture that declared a holiday just for qualifying in 2018.",
    sights: ["Panama Canal (Miraflores Locks)", "San Blas / Guna Yala islands", "Casco Viejo, Panama City"],
    foods: ["Sancocho", "Ceviche at the fish market", "Patacones"],
    culture: "Pollera dresses and diablico masks at carnival, mola textiles of the Guna people, salsa legend Rubén Blades.",
    legends: ["Rubén Blades... of football: Román Torres", "Adalberto Carrasquilla", "Ismael Díaz"],
    wc: "2nd appearance after Russia 2018.",
    fact: "Ships pay up to $500,000+ for one Panama Canal transit. Swimmers: not allowed.",
    status: "🟥 ELIMINATED IN GROUP L."
  }
};

/* ---- Real change (away) kits for well-known sides.
   Any team not listed gets a distinct auto-generated away kit (see app.js). ---- */
const KITS_AWAY = {
  bra: { p:"#1a3fb0", s:"#FFDC00", pattern:"solid", shorts:"#1a3fb0", socks:"#FFFFFF" },
  arg: { p:"#15152e", s:"#75AADB", pattern:"solid", shorts:"#15152e", socks:"#15152e" },
  fra: { p:"#F5F5F5", s:"#001E62", pattern:"solid", shorts:"#001E62", socks:"#F5F5F5" },
  esp: { p:"#1b2a6b", s:"#F1BF00", pattern:"solid", shorts:"#1b2a6b", socks:"#1b2a6b" },
  por: { p:"#F5F5F5", s:"#E42518", pattern:"solid", shorts:"#F5F5F5", socks:"#E42518" },
  ger: { p:"#1f7a48", s:"#FFFFFF", pattern:"solid", shorts:"#0b3d24", socks:"#1f7a48" },
  ned: { p:"#16266b", s:"#FF6600", pattern:"solid", shorts:"#16266b", socks:"#16266b" },
  eng: { p:"#C8102E", s:"#FFFFFF", pattern:"solid", shorts:"#C8102E", socks:"#C8102E" },
  mex: { p:"#101010", s:"#046A38", pattern:"solid", shorts:"#101010", socks:"#101010" },
  usa: { p:"#15193a", s:"#FFFFFF", pattern:"solid", shorts:"#15193a", socks:"#15193a" },
  bel: { p:"#F2D400", s:"#000000", pattern:"solid", shorts:"#000000", socks:"#F2D400" },
  mar: { p:"#F5F5F5", s:"#C1272D", pattern:"solid", shorts:"#F5F5F5", socks:"#C1272D" },
  uru: { p:"#0a1a3a", s:"#FFFFFF", pattern:"solid", shorts:"#0a1a3a", socks:"#0a1a3a" },
  cro: { p:"#0a1226", s:"#FFFFFF", pattern:"checks", shorts:"#0a1226", socks:"#0a1226" },
  jpn: { p:"#F5F5F5", s:"#003DA5", pattern:"solid", shorts:"#F5F5F5", socks:"#F5F5F5" },
  nor: { p:"#0a1a4a", s:"#FFFFFF", pattern:"solid", shorts:"#0a1a4a", socks:"#0a1a4a" },
  sen: { p:"#00853F", s:"#FDEF42", pattern:"solid", shorts:"#00853F", socks:"#00853F" },
  gha: { p:"#CE1126", s:"#FCD116", pattern:"solid", shorts:"#CE1126", socks:"#CE1126" },
  col: { p:"#0a1a5a", s:"#FCD116", pattern:"solid", shorts:"#0a1a5a", socks:"#0a1a5a" },
  sui: { p:"#101426", s:"#DA291C", pattern:"solid", shorts:"#101426", socks:"#101426" }
};

/* Group order for rosters/standings */
const GROUP_ORDER = ["A","B","C","D","E","F","G","H","I","J","K","L"];
